### PR TITLE
Added hability to override gav

### PR DESCRIPTION
**Pull request by rmpestano**
Hi @aslakknutsen,

I added a way to override chameleon gav by:

1. adding **chameleonGav** property; 
2. after adaper is resolved I just change its distribution to the provided gav.

Do you think its sufficient for #41? 

I've tested here at the company with our custom distribution and it works great, here is our arquillian.xml:

```
 <property name="chameleonGav">com.procergs:jboss-eap-dist:zip:6.4.Final</property>
 <property name="chameleonTarget">jboss eap:6.4.Final:${arquillian.container}</property>
```

no need for custom containers.yaml.

WDYT?

---
This change is [Reviewable](https://reviewable.io/reviews/arquillian/arquillian-container-chameleon/42)

### CODE REVIEW

**Comment by rmpestano** [comment]
hmm looking at your comment on issue [#40](https://github.com/arquillian/arquillian-container-chameleon/issues/40#issuecomment-187676017) I see your idea was not to create a new property, what do you had in mind for this issue?

**Comment by aslakknutsen** [comment]
@rmpestano My first thought was to allow to load a file named e.g. 'override-default-containers.yaml'  from classpath that the Chameleon internals would merge on top of the built-in default configuration. That way you could provide your company jar that contains this file and overrides any configuration option for any container.

**Comment by rmpestano** [comment]
@aslakknutsen, well if I still need to provide a jar with containers.yaml then I have no problems with current approach (copy default.yaml and change gav).

With the approach in this PR only a property is needed.

**Comment by rmpestano** [comment]
Hi @aslakknutsen, 

I think we can close the issue, I'm assuming its not a common use case (no one comment the pr).

Anyaway we are keeping our "custom" chameleon in our company maven repository.

**Comment by bartoszmajsak** [comment]
> With the approach in this PR only a property in arq.xml is needed, no need to know containers.yaml syntax or its properties [...]
> [...] Anyway we are keeping our "custom" chameleon in our company maven repository.

But wouldn't it be enough for your use to define custom container (like we have in the tests) instead and override certain properties? Diverging from the upstream dev will make your life harder I believe :)

That said - shall we close it? @aslakknutsen

**Comment by aslakknutsen** [comment]
+1

**Comment by rmpestano** [comment]
Hi guys,

we have custom eap distribution here at the company. It has custom modules and patches applied.

How do you configure chameleon without having a custom yaml file on each application?

**Comment by bartoszmajsak** [comment]
Shouldn't this YAML be on the classpath this way or the other? Maybe shipping it as a JAR would be sufficient? Can you try this approach?

**Comment by rmpestano** [comment]
One approach is to bundle the yaml into a jar and use it as dependency as [discussed here](https://github.com/arquillian/arquillian-container-chameleon/issues/40#issue-135562116). Its not the simpler way because it introduces another dependency when we could just change a property in arquillian.xml

**Comment by rmpestano** [comment]
Hi @bartoszmajsak, yes (answered at the same time), it solves the issue but for us its way better to manage arq.xml property instead of generating another version  of this dependency(which just changes the adapter's **gav**  in yaml) everytime a patch is applied to jboss.

**Comment by bartoszmajsak** [comment]
Didn't check #40 issue. But then maybe instead of making a special property for GAV we can support syntax in YAML with defaulting. So you would have your one custom jar with this YAML file and having

```
gav: ${version.glassfish:org.glassfish.main.distributions:glassfish:zip:${version}}
```
Would it make sense @aslakknutsen @rmpestano?

**Comment by rmpestano** [comment]
that's nice but why not support the `${version}` directly in chameleon core?

**Comment by rmpestano** [comment]
well in fact the hole gav instead of version

**Comment by bartoszmajsak** [comment]
We could think about evaluating `${variables}` in YAML like we do in `arquillian.xml`, but then maybe #41 is better way of doing that?

**Comment by rmpestano** [comment]
Nice, I am :+1: for any solution that allows me to update container version without managing additional .yaml files or dependencies. 

May I close this PR?

**Comment by bartoszmajsak** [comment]
> May I close this PR?

Go ahead. 

Keen to hack on #41 btw? :)

**Comment by rmpestano** [comment]
> Keen to hack on #41 btw? :)

sure but its a bit nebulous to me on how ${variables} substitution works, example I imagine we would have a gav variable in default containers.yaml:


```
- name: wildfly
  versionExpression: 9.*
  adapters:
    - type: managed
      gav: org.wildfly.arquillian:wildfly-arquillian-container-managed:1.0.0.Final
      adapterClass: org.jboss.as.arquillian.container.managed.ManagedDeployableContainer
      configuration: &WF_CONFIG
        jbossHome: ${dist}
  dist: &WF_DIST
    gav: ${gav}
```

and arq.xml:

```
 <container qualifier="chameleon" default="true">
    <configuration>
      <property name="chameleonTarget">wildfly:9.0.0.Final:managed</property>
    </configuration>
  </container>
```

if no gav variable provided then use default one: `org.wildfly:wildfly-dist:zip:${version}`


But how do we override default *gav* in this case? same way the version is extracted from [gav today](https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/resources/chameleon/default/containers.yaml#L47)? in this case the gav should be part of cameleon target property, or do you have another idea?

**Comment by bartoszmajsak** [comment]
Let's move this discussion to forum

**Pull request closed without merging**
