### PR TITLE
Move Profile configuration to yaml file

### LINKED ISSUE #6: investigate how to provide resolution for arbitrary container
I guess we should not leave Android containers behind. I know it is pretty specific but Droidium provides the first class container itself so why not to support that really ...

### PR DESCRIPTION
**Pull request by aslakknutsen**
* Replace Profile with new ContainerAdapter model

fixes #6

### CODE REVIEW

**Comment by aslakknutsen** [comment]
containers.json currently only contain wildfly 8 and 9 remote|managed|embedded configuration.

**Comment by lfryc** [comment]
do you think we should extend it for EAP / JBoss AS as in Alpha1?

**Comment by aslakknutsen** [comment]
@lfryc of course. Just added a few to give the general idea of the format to see if anyone had any comments :)

**Comment by aslakknutsen** [comment]
pushed upstream https://github.com/arquillian/arquillian-container-chameleon/commit/b37fc6791dea46f519093320e2f0605c9a50c573

**Pull request closed without merging**
